# Generated by Django 4.0.5 on 2022-08-05 15:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('assesment_title', models.CharField(max_length=255, null=True)),
                ('available_time', models.TimeField(blank=True, null=True)),
                ('available_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('cohortName', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=255)),
                ('cohortName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.examcohort')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='saveViva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vivaQuestion', models.CharField(max_length=255, null=True)),
                ('vivaMark', models.FloatField(blank=True, null=True)),
                ('qv_type', models.CharField(max_length=50, null=True)),
                ('assessmentTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.assestment')),
                ('cohortName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.examcohort')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='saveExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True)),
                ('optionA', models.CharField(max_length=255, null=True)),
                ('optionB', models.CharField(max_length=255, null=True)),
                ('optionC', models.CharField(max_length=255, null=True)),
                ('optionD', models.CharField(max_length=255, null=True)),
                ('selectedAns', models.CharField(max_length=255, null=True)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('assessmentTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.assestment')),
                ('cohortName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.examcohort')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True)),
                ('optionA', models.CharField(max_length=255, null=True)),
                ('optionB', models.CharField(max_length=255, null=True)),
                ('optionC', models.CharField(max_length=255, null=True)),
                ('optionD', models.CharField(max_length=255, null=True)),
                ('correctAns', models.CharField(max_length=255, null=True)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('q_type', models.CharField(max_length=50, null=True)),
                ('assessmentTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.assestment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='assestment',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.examcohort'),
        ),
    ]
