# Generated by Django 4.0.5 on 2022-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveviva',
            name='audiofile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
