# Generated by Django 4.0.5 on 2022-08-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_saveexamrecord_questype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveexamrecord',
            options={'ordering': ['-user']},
        ),
    ]
