# Generated by Django 4.1 on 2022-09-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_saveexamrecord_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveviva',
            name='audiofile',
        ),
    ]
